### ISSUE TITLE
Unicode Support

### ISSUE THREAD

**Issue by benmmurphy** [deadtrickster/ssl_verify_hostname.erl#8]
So I think unicode support will work with dNSName because dNSName is effectively limited to ascii and will always have punicode names in ssl:connect(Host) because erlang doesn't have support for unicode name resolution. However, some CAs will put unicode in the common name field. So you need a way of converting unicode->punycode to do the correct matching for common name certs. More details here: https://bugzilla.mozilla.org/show_bug.cgi?id=280839

**Comment by deadtrickster** [comment]
Can you give me an example where CN has unicode encoded hostname [it has to be added to test certs anyway]? I have a feeling that today most certificates generated with proper altName and maybe it copied to CN for backward compatibility. Also we are looking at CN only if altNames are not present. So it has to be very interesting case: certificate without altName but with hostname presented in CN and unicode encoded, right?

**Comment by benmmurphy** [comment]
yeah i think you are right and this is not a problem. i don't think firefox handles this so i don't see the point of handling it erlang.
